[package]
name = "program-simulator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "program_simulator"


[dependencies]
solana-sdk = {version = "2.0.15"}
solana-client = {version = "2.0.15"}
solana-program-test = {version = "2.0.15"}
solana-program ={version = "2.0.15"}
bincode = "*"
borsh = "*"
anchor-lang = ">=0.28.0"
